In [31]:
import h5py
import pandas as pd
import matplotlib
import matplotlib.pyplot as plt
import numpy as np
import glob, os
import datetime as dt
import cv2
from scipy.signal import find_peaks, peak_prominences
import ffmpeg
import subprocess
import math

In [32]:
%run -i '/home/ml/Documents/rung_functions.py'

In [81]:
%run -i '/home/ml/Documents/mp_rung_scores.py'

/home/ml/Documents/mp_rung_scores.py:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  folders+=glob.glob("/home/ml/Documents/Not_TADSS_Videos/"+rat+"/cut/dlc_output_16-810/*.h5")


ValueError: array size of lower interval border must match x

In [45]:
%run -i '/home/ml/Documents/multipointgraphs.py'

NameError: name 'score_df' is not defined

In [12]:
find_peaks(df_fingers['y'],height=663)

(array([], dtype=int64), {'peak_heights': array([], dtype=float64)})

In [16]:
pd.read_hdf("/"+rung_folder+"/"+rung_file+"_"+"DLC_resnet50_LadderWalkMar12shuffle1_350000.h5")

scorer    DLC_resnet50_LadderWalkMar12shuffle1_350000                         \
bodyparts                                      rung_1                          
coords                                              x           y likelihood   
0                                           96.297829  639.754517   0.054013   
1                                           96.066071  640.359070   0.033941   
2                                           95.649330  639.392090   0.042431   
3                                           96.332382  639.284119   0.036062   
4                                           96.938622  642.091309   0.047046   
5                                           95.761444  639.375244   0.017936   
6                                           95.550140  639.383972   0.022205   
7                                           95.072746  639.308716   0.038417   
8                                           95.064880  638.974182   0.032677   
9                                           96.214714  639.693481   0.031654   
10                                          96.469940  640.439941   0.029756   
11                                          96.275345  640.676453   0.025240   
12                                          96.240875  640.173523   0.015929   
13                                          95.755882  639.622253   0.048065   
14                                          96.043938  640.035767   0.039687   
15                                          95.793304  640.836121   0.038230   
16                                          94.712967  641.126953   0.027661   

scorer                                                                \
bodyparts      rung_2                             rung_3               
coords              x           y likelihood           x           y   
0          108.198944  642.226196   0.042031  134.161362  641.032471   
1          114.265221  642.293396   0.038297  133.415863  640.905212   
2          110.607002  641.895630   0.039817  133.247940  640.687195   
3          110.439278  641.203064   0.028316  132.947739  640.313049   
4          110.908890  641.716858   0.050365  133.185410  640.391907   
5          114.564232  641.570251   0.021801  133.777527  640.282043   
6          114.732300  641.830566   0.027614  133.266830  640.686340   
7          114.464821  641.458191   0.035771  133.167892  640.594116   
8          114.566437  641.508484   0.037144  133.774536  640.811279   
9          114.145020  642.098572   0.028746  133.006714  640.896667   
10         114.111000  642.589417   0.029354  132.916946  640.956055   
11         113.688591  642.170227   0.026068  132.359848  640.812683   
12         114.350227  641.737305   0.019850  133.089554  640.515076   
13         110.619019  641.220642   0.062339  132.423004  640.735718   
14         108.559410  641.356079   0.046410  133.705307  640.532898   
15         108.555138  641.546448   0.031764  133.750610  641.103149   
16         108.020287  641.367004   0.033557  133.721268  641.009338   

scorer                            ...                                      \
bodyparts                 rung_4  ...    rung_59      rung_60               
coords    likelihood           x  ... likelihood            x           y   
0           0.546247  147.029068  ...   0.094013  1803.823853  633.688110   
1           0.245239  147.430664  ...   0.059906  1803.931641  633.487549   
2           0.329943  146.383133  ...   0.057383  1804.760864  632.880981   
3           0.175530  146.200851  ...   0.081228  1849.976929  638.899170   
4           0.277761  146.160385  ...   0.080893  1805.564209  633.296387   
5           0.204545  147.207123  ...   0.084766  1802.135254  633.796814   
6           0.237733  146.740692  ...   0.121255  1804.468628  632.934143   
7           0.272925  146.867416  ...   0.192154  1851.490723  639.855042   
8           0.305387  146.919067  ...   0.119945  1850.643188  638.993591   
9           0.275772  146.589447  

In [88]:
step_indexes = []
for x in df_fingers['x']:
    diff = abs(rung_x-x)
    ind = (np.where(diff<10))
    step_indexes.append(ind[0])

/home/ml/Documents/mp_rung_scores.py:4: RuntimeWarning: invalid value encountered in less
  left_handed = []


In [89]:
step_indexes

[array([], dtype=int64),
 array([], dtype=int64),
 array([], dtype=int64),
 array([37]),
 array([35]),
 array([35]),
 array([35]),
 array([31]),
 array([31]),
 array([31]),
 array([], dtype=int64),
 array([], dtype=int64),
 array([], dtype=int64),
 array([], dtype=int64),
 array([ 0, 17, 18]),
 array([ 0, 18]),
 array([ 0, 17, 18])]

In [90]:
f

'/home/ml/Documents/Not_TADSS_Videos/MC45/cut/dlc_output_16-810/MC45_7-17-19_L4_crossing8_patternB_light1_DLC_resnet101_LadderWalkFeb13shuffle1_1030000.h5'